### ISSUE TITLE
Using `buffer-match-p` to consolidate user options

### ISSUE THREAD

**Issue by krisbalintona** [jamescherti/buffer-terminator.el#2]
Buffer-terminator has many user options to control which buffers are killed. They are the `buffer-terminator-keep-* and `buffer-terminator-kill-*` options.

My proposal is that I think these options can all be centralized to just one or two variables that covers more than the current set of options do. The value of this variable would be supplied to `buffer-match-p` to determine whether a buffer should be killed or not. `buffer-match-p` is what `display-buffer-alist` uses to match buffers. It accepts regular expressions, predicate functions, and cons-cells that take major-mode, category, and derive-mode (alongside operators like and, or, and not).

With the current options, it is hard to even, e.g., match buffers that are listed in `org-agenda-files`.

**Comment by jamescherti** [comment]
What are you trying to achieve? Could you specify which buffers you want to close and which ones you prefer to keep in your configuration?

**Comment by jamescherti** [comment]
I also recommend you to try the following in the latest version of buffer-terminator (main branch):

You can set a custom predicate function using `buffer-terminator-predicate` to control which inactive buffers the *buffer-terminator* should keep or kill based on specific conditions.

Here is an example of how to define a custom predicate function:

``` elisp
(defun my-buffer-terminator-predicate (buffer)
  "Function to decide the fate of a buffer.
This function takes a single argument, BUFFER, and can return one of the
following values:
:kill    Indicates that the buffer should be killed.
:keep    Indicates that the buffer should be kept.
nil      Let Buffer-Terminator decide."
  (let ((buffer-name (buffer-name buffer)))
    (cond
     ;; Kill the scratch buffer
     ((string= buffer-name "*scratch*")
      :kill)

     ;; Keep this buffer:
     ((string= buffer-name "my-precious-buffer")
      :keep)

     (t
      ;; Nil = Buffer-Terminator decides
      nil))))

(setq buffer-terminator-predicate #'my-buffer-terminator-predicate)
```

**Comment by jamescherti** [comment]
> My proposal is that I think these options can all be centralized to just one or two variables that covers more than the current set of options do. The value of this variable would be supplied to buffer-match-p to determine whether a buffer should be killed or not. buffer-match-p is what display-buffer-alist uses to match buffers. It accepts regular expressions, predicate functions, and cons-cells that take major-mode, category, and derive-mode (alongside operators like and, or, and not).

That's a good idea. However, I wonder if simply providing a predicate function could serve as an alternative to these variables.

**Comment by gavv** [comment]
IMHO the approach suggested by @krisbalintona would be a bit more convenient than `buffer-terminator-predicate`.

I think most implementations of `buffer-terminator-predicate` would just match buffer name by regexp or major mode. So it would be convenient if I don't need to write the matching code by hand and can just provide e.g. regexps. And since predicates are supported too, this suggested approach is not inferior to `buffer-terminator-predicate`.

Another good thing that in documentation you can say "matching works like display-buffer-alist", and those familiar with it would immediately know how to use it.

**Comment by jamescherti** [comment]
Thank you for your suggestions, @gavv and @krisbalintona. I've added this to my to-do list and will consider an implementation approach. A design similar to `display-buffer-alist` would likely be intuitive for users. Feel free to share code suggestions on how you would implement this while maintaining user accessibility.

**Comment by jamescherti** [comment]
Maybe something like:
```elisp
(setq my-buffer-rules
      '((:keep-buffer-name . "important-buffer")
        (:kill-buffer-name . "temporary-buffer")
        (:keep-buffer-name-regexp . "^\\*scratch\\*$")
        (:kill-buffer-name-regexp . "^\\*.*\\*$")))
```

This approach would allow users to define and control the order in which buffers are kept or killed.

**Comment by jamescherti** [comment]
I have implemented this feature. You can try it in the `develop` branch.

@gavv @krisbalintona Could you please try it before it gets merges into the `main` branch?

**Comment by krisbalintona** [comment]
@jamescherti Thanks for putting together an implementation so quickly. I'll try out the develop branch over the next few days and will get back to you on my thoughts.

**Comment by jamescherti** [comment]
> @jamescherti Thanks for putting together an implementation so quickly. I'll try out the develop branch over the next few days and will get back to you on my thoughts.

You're very welcome, @krisbalintona!

I plan to merge it into the `master` branch in a few hours. However, I am still interested to hear your feedback.

**Comment by krisbalintona** [comment]
So far, I think this implementation is an improvement on the master branch. The many user options are consolidated into a single option, `buffer-terminator-rules-alist`, and you added a predicate option, `buffer-terminator-predicate`. I do, however, still have two comments.

1. I still think using`buffer-match-p` is preferable because it seems to cover all the cases that are now covered with the two options above while (I) being used by the familiar `display-buffer-alist` and (II) would allow for ergonomically combining the two options into one. For instance, `buffer-terminator-rules-alist` currently accepts a list of cons cells where the car of each cell is a pre-defined "rule." Rather than accepting buffer-terminator's bespoke rules, we could simply accept a `buffer-match-p` form. The cons of the cells, then, could be `:keep`, `:kill`, or `nil`, the values `buffer-terminator-predicate` accepts. What do you think of this implementation?
2. A more minor point: it is not obvious (without going through the documentation) which buffers buffer-terminator kills and keeps by default. I think a good QoL change would be migrating the default behavior into the default value of whatever user options there are for kill and keeping buffers (e.g., `buffer-terminator-rules-alist`). That way, the considerations and behavior of the package are more transparent to users.

**Comment by jamescherti** [comment]
Thanks for your suggestions. I'll see how these could > I still think usingbuffer-match-p is preferable because it seems to cover all the cases that are now covered with the two options above while (I) being used by the familiar display-buffer-alist and (II) would allow for ergonomically combining the two options into one. For instance, buffer-terminator-rules-alist currently accepts a list of cons cells where the car of each cell is a pre-defined "rule." Rather than accepting buffer-terminator's bespoke rules, we could simply accept a buffer-match-p form. The cons of the cells, then, could be :keep, :kill, or nil, the values buffer-terminator-predicate accepts. What do you think of this implementation?

I think I'll keep the implementation as it is for now because it allows for maintaining an order and specifying a list of rules (which have priority). `display-buffer-alist` only supports regular expressions as keys, whereas `buffer-terminator-rules-alist` offers more flexibility by allowing the definition of any rules, including the addition of new ones in the future. A new rule could also be a predicate function or simply a function like `buffer-match-p`.

> A more minor point: it is not obvious (without going through the documentation) which buffers buffer-terminator kills and keeps by default. 

**Here is a quote from the README.md file:**

By default, all inactive buffers are terminated except special buffers. (For Buffer-Terminator, special buffers whose names start with a space, start and end with `*`, and buffers whose major mode is derived from `special-mode`).

When a buffer is not a special buffer (e.g., a file-visiting or dired buffer), only buffers that have been inactive for a specified period are terminated. (Exception: modified file-visiting buffers that have not been saved are not terminated; the user must save them first.)"

When you define a predicate function or rules, it superseeds the above rules.

> I think a good QoL change would be migrating the default behavior into the default value of whatever user options there are for kill and keeping buffers (e.g., buffer-terminator-rules-alist). That way, the considerations and behavior of the package are more transparent to users.

Yes, that's a good idea. I'll need to think it over, and I may add most of the items as a list of rules.

**Comment by jamescherti** [comment]
> I think a good QoL change would be migrating the default behavior into the default value of whatever user options there are for kill and keeping buffers (e.g., buffer-terminator-rules-alist). That way, the considerations and behavior of the package are more transparent to users.

Here is an possible implementation to replace `buffer-terminator-keep-buffers-with-process`, `buffer-terminator-keep-visible-buffers`, `buffer-terminator-keep-file-visiting-buffers`, and `buffer-terminator-keep-special-buffers`:

(setq my-buffer-rules
      '((keep-buffer-type . process)
        (keep-buffer-type . file)
        (keep-buffer-type . visible)
        (keep-buffer-type . special)
        (keep-buffer-name . "important-buffer")
        (kill-buffer-name . "temporary-buffer")
        (keep-buffer-name-regexp . "\\` \\*markdown-code-fontification:.*\\*\\'")
        (kill-buffer-name-regexp . "\\` \\*stderr of ")))

**Comment by jamescherti** [comment]
Take a look at the latest develop branch:

The default is now:
```elisp
(setq buffer-terminator-rules-alist
      '(;; Visible buffers
        (keep-buffer-status . "visible")

        ;; NEVER REMOVE special buffers unless you know what you are doing.
        (keep-buffer-status . "special")))
```

It is more transparent.

You can add more rules to the default value above:
```elisp
(setq buffer-terminator-rules-alist
      '((kill-buffer-name . ("temporary-buffer-name1"
                             "temporary-buffer-name2"))

        (keep-buffer-name . ("important-buffer-name1"
                             "important-buffer-name2"))

        ;; Users can also define strings
        (kill-buffer-name . "temporary-buffer-name3")

        (keep-buffer-name-regexp . ("\\` \\*Minibuf-[0-9]+\\*\\'"))
        (kill-buffer-name-regexp . "compile-angel")

        ;; Visible buffers
        (keep-buffer-status . "visible")

        ;; NEVER REMOVE special buffers unless you know what you are doing.
        (keep-buffer-status . "special")))
```

**Comment by gavv** [comment]
> I think I'll keep the implementation as it is [...]. display-buffer-alist only supports regular expressions as keys, whereas buffer-terminator-rules-alist offers more flexibility by allowing the definition of any rules, including the addition of new ones in the future. A new rule could also be a predicate function or simply a function like buffer-match-p.

Here is a snippet from `display-buffer-alist` docstring:

```
If non-nil, this is an alist of elements (CONDITION . ACTION),
where:

 CONDITION is either a regexp matching buffer names, or a
  function that takes two arguments - a buffer name and the
  ACTION argument of display-buffer - and returns a boolean.
```

And this is from `buffer-match-p` docstring:

```
CONDITION is either:
- the symbol t, to always match,
- the symbol nil, which never matches,
- a regular expression, to match a buffer name,
- a predicate function that takes a buffer object and ARG as
  arguments, and returns non-nil if the buffer matches,
- a cons-cell, where the car describes how to interpret the cdr.
  The car can be one of the following:
  * `derived-mode': the buffer matches if the buffer's major mode
    is derived from the major mode in the cons-cell's cdr.
  * `major-mode': the buffer matches if the buffer's major mode
    is eq to the cons-cell's cdr.  Prefer using `derived-mode'
    instead when both can work.
  * `not': the cadr is interpreted as a negation of a condition.
  * `and': the cdr is a list of recursive conditions, that all have
    to be met.
  * `or': the cdr is a list of recursive condition, of which at
    least one has to be met."
```

So, actually CONDITION in `buffer-match-p` may be: `t`, `nil`, `"regexp"`, `#'function`, `'(derived-mode MODE)`, `'(major-mode MODE)`, and also expressions with `and`, `or`, `not`, and recursive conditions. It's a kind of mini-language for buffer matching.

I think the approach suggested by @krisbalintona is to make `buffer-terminator-rules-alist` list of pairs `(CONDITION . ACTION)`, where CONDITION is the same thing as above (and is passed to `buffer-match-p`), and ACTION is some symbol specific to buffer-terminator, e.g. `:kill` or `:keep`.

This would preserve the order and allow both regexps and predicates, as well as other convenient conditions. Also your matching code will be simpler because you can just reuse `buffer-match-p` and call it for every CONDITION.

With this approach, your last example could be translated to something like this:

```
(setq buffer-terminator-rules-alist
    '(((or "temporary-buffer-name1" "temporary-buffer-name2") . :kill)
      ((or "important-buffer-name1" "important-buffer-name2") . :keep)

      ("temporary-buffer-name3" . :kill)

      ("\\` \\*Minibuf-[0-9]+\\*\\'" . :keep)
      ("compile-angel" . kill)

      (buffer-terminator-process-buffer-p . :keep)
      (buffer-terminator-special-buffer-p . :keep)
      (buffer-terminator-visible-buffer-p . :keep)

      (t . :kill)))
```

(Here, `buffer-terminator-*-buffer-p` are builtin predicate functions provided by the package.)

I guess technically this approach is similar to the current one, however it would be more familiar to users and documentation would be simpler (you can just refer to `buffer-match-p`).

Also support for expressions like `(major-mode MODE)` and logical operators is quite handy, you can define your rules a in declarative way without writing code, and still have some simple logic.

**Comment by jamescherti** [comment]
Thank you for your thorough explanation. However, I have already invested time in the current implementation. It is working and you can test it in the develop branch. For now, I will keep it as it is, as I need to test the current implementation before merging it into the master branch.

**Comment by krisbalintona** [comment]
@gavv Thank you for explaining what I meant better than I could. You are spot on.

@jamescherti Your current implementation should be just as functionality. Although I still prefer the ergonomics of `buffer-match-p`, the merits being explained by @gavv's previous comment, but I think your decision to keep the current implementation is reasonable.

**Comment by jamescherti** [comment]
> but I think your decision to keep the current implementation is reasonable.

Thank you for your feedback, @krisbalintona and @gavv.

Just in case you are interested, here is how it looks in the latest version (develop branch) that will be merged into master:

Default value:
```elisp
(setq buffer-terminator-rules-alist
      '((keep-buffer-property . special)
        (keep-buffer-property . process)
        (keep-buffer-property . visible)
        (kill-buffer-property . inactive)
        (return . :kill)))
```

Example of other values:
```elisp
(setq buffer-terminator-rules-alist
      '((kill-buffer-name . ("temporary-buffer-name1"
                             "temporary-buffer-name2"))

        (keep-buffer-name . ("important-buffer-name1"
                             "important-buffer-name2"))

        ;; Users can also define strings
        (kill-buffer-name . "temporary-buffer-name3")

        (keep-buffer-name-regexp . ("\\` \\*Minibuf-[0-9]+\\*\\'"))
        (kill-buffer-name-regexp . "compile-angel")

        ;; Retain special buffers (Important).
        ;; Keep this before kill-buffer-property: inactive and visible.
        ;;
        ;; (If you choose to kill special buffers by removing the following,
        ;; ensure that the special buffers you want to keep are added
        ;; keep-buffer-name rules above.)
        ;;
        ;; DO NOT REMOVE special buffers unless you know of what you are doing.
        (keep-buffer-property . special)

        ;; Keep process buffers
        ;; Process buffers are buffers where an active process is running.
        ;; Removing the following will result in the termination of such
        ;; buffers, potentially disrupting active processes.
        (keep-buffer-property . process)

        ;; Retain visible buffers are those currently displayed in any window.
        ;; Keep this in the end, after all the rules above.
        ;; It is generally discouraged to set this to nil, as doing so may result
        ;; in the termination of visible buffers, except for the currently active
        ;; buffer in the selected window.
        ;;
        ;; DO NOT REMOVE visible buffers unless necessary.
        (keep-buffer-property . visible)

        ;; Kill the buffers that have been inactive.
        ;; Keep this in the end, after all the rules above.
        ;; This can be customized with `buffer-terminator-inactivity-timeout`
        ;; and `buffer-terminator-interval`.
        (kill-buffer-property . inactive)

        ;; Call a function that decides the fate of a buffer. It returns:
        ;;   :kill    Indicates that the buffer should be killed.
        ;;   :keep    Indicates that the buffer should be kept.
        ;;   nil      Let Buffer-Terminator decide.
        ;; (call-function . function-name)

        ;; Kill the remaining buffers that were not retained by previous rules
        (return . :kill)))
```

**Comment by jamescherti** [comment]
FYI: The new feature has been merged into master.

**Comment by gavv** [comment]
Thanks, I've updated and will keep an eye on how it behaves. For now seems doing its job.

For the record, here is my current configuration:

```elisp
(require 'buffer-terminator)

(setq buffer-terminator-verbose t
      buffer-terminator-inactivity-timeout (* 120 60) ; 120 min
      buffer-terminator-interval (* 30 60) ; 30 min
      )

(setq my-term:allow-kill-list
      (list
       ;; ui
       (pcre "^\\*Pp Eval Output\\*$")
       (pcre "^\\*Backtrace\\*$")
       (pcre "^\\*Disabled Command\\*$")
       (pcre "^\\*Customize Option:.*\\*$")
       (pcre "^\\*Completions\\*$")
       (pcre "^\\*Occur\\*$")
       (pcre "^\\*xref\\*$")
       (pcre "^\\*Org.*\\*$")
       ;; docs
       (pcre "^\\*Colors\\*$")
       (pcre "^\\*Help\\*$")
       (pcre "^\\*helpful.*\\*$")
       (pcre "^\\*WoMan.*\\*$")
       (pcre "^\\*info\\*$")
       (pcre "^\\*devdocs.*\\*$")
       (pcre "^\\*tldr.*\\*$")
       (pcre "^\\*lsp-help.*\\*$")
       ;; tools
       (pcre "^magit:.+$")
       (pcre "^magit-log.*$")
       (pcre "^magit-diff.*$")
       (pcre "^magit-revision.*$")
       (pcre "^\\*rg.*\\*$")
       (pcre "^\\*tramp/.+\\*$")
       (pcre "^\\*vterminal.*\\*$")
       (pcre "^\\*ielm.*\\*$")
       ))

(defun my-term:kill-buffer-p ()
  (let* ((buffer-name (buffer-name))
         (is-internal (string-prefix-p " " buffer-name))
         (is-special (or (string-match-p (pcre "^\\*.+\\*.*$") buffer-name)
                         (derived-mode-p 'special-mode)))
         (is-process (get-buffer-process (current-buffer)))
         (is-file (or (buffer-file-name (buffer-base-buffer))
                      (derived-mode-p 'dired-mode))))
    (cond
     ;; never kill internal buffers
     (is-internal :keep)
     ((or is-special is-process (not is-file))
      (if (seq-some
           (lambda (re) (string-match-p re buffer-name))
           my-term:allow-kill-list)
          ;; probably kill special buffers from allow list
          nil
        ;; never kill other special buffers
        :keep))
     ;; probably kill other buffers
     (t nil))))

(setq buffer-terminator-rules-alist
      '(
        (call-function . my-term:kill-buffer-p)
        (keep-buffer-property . visible)
        (kill-buffer-property . inactive)
        ))

(buffer-terminator-mode 1)
```

Note: I wasn't able to reuse most of the builtin rules (special, process, regexps) to express this logic and had to write one big predicate function instead, which duplicates some code from buffer-terminator. That's because buffer-terminator-rules-alist doesn't allow combining rules with logical operations, unlike buffer-match-p :smiling_face_with_tear: 

Another note: I'm matching special buffers as `*text*maybe_more_text` instead of `*text*`, because on my setup some buffers are named so (probably that's incorrect, but so it is), for example: `*compilation*<roc-toolkit>` (by project-compile), `*assistant* gpt4/Seasoned` (by chatgpt-shell).

Also, I have added `(not is-file)` check, but I'm not sure if it's really needed.

**Comment by jamescherti** [comment]
Thanks for the update and for sharing your customizations! It's always inspiring to see how others tailor their setups. Feel free to reach out if you encounter any issues. I'm happy to help with further troubleshooting or refinement.
